### ISSUE TITLE
kapt(mn.micronaut.openapi) breaks incremental annotation processing

### ISSUE THREAD

**Issue by Spikhalskiy** [micronaut-projects/micronaut-openapi#1101]
### Expected Behavior

An addition of `kapt(mn.micronaut.openapi)` to the gradle build configuration doesn't lead to extreme changes in incremental build time

### Actual Behaviour

An addition of `kapt(mn.micronaut.openapi)`
leads to extremely slow rebuild time with any small change, which is disruptive for the execution of single tests from IDE. 
The following warnings are new during the build process:

```
> Task :kaptKotlin
[WARN] Issue detected with io.micronaut.annotation.processing.TypeElementVisitorProcessor. Expected 1 originating source file when generating <>/build/generated/source/kapt/main/dummy12600902257963, but detected 0: [].
Note: Generating OpenAPI Documentation
...
Note: Writing OpenAPI file to destination: <>/build/tmp/kapt3/classes/main/META-INF/swagger/<>-2.0.yml
Note: Writing OpenAPI views to destination: <>/build/tmp/kapt3/classes/main/META-INF/swagger/views
[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: io.micronaut.annotation.processing.TypeElementVisitorProcessor (DYNAMIC).
```

### Version

micronaut-bom 3.9.4, which brings micronaut-openapi:3.8.7
Also reproduces with an upgrade to micronaut-openapi:4.9.2

### Additional context

[Potentially relevant issue](https://github.com/micronaut-projects/micronaut-core/issues/9148)

**Comment by altro3** [comment]
@Spikhalskiy  Hi! The problem is that there is no normal way in the annotation processor to find out the current project directory. Micronaut uses a little hack to do this - he tries to generate a dummy file to determine the current directory, then deletes it. But kapt doesn't like this mechanism.

The only normal solution that I could come up with is to give the opportunity to set the project directory manually, then a dummy file will not be created and there will be no problems.

Now it will be enough to write like this:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/2f61b061-2690-4a48-9a12-1b8089ddd9e2)
And there will be no more problems. Wait for release 4.10.0
