### ISSUE TITLE
Micronaut 4.0.x does not set type:object for maps 

### ISSUE THREAD

**Issue by mdavis95** [micronaut-projects/micronaut-openapi#1175]
### Expected Behavior

A map<string,string> should generate
```
   type: object
   additionalProperties:
      type: string
```
as it did with Micronaut 3.x

### Actual Behaviour

A map<string,string> generates
```
   additionalProperties:
      type: string
```

### Steps To Reproduce

Use micronaut launch and select openapi and micronaut 4.0.x.

Generate a simple dto such as
```
public class SimpleDto {
	private Map<String, String> tags;
	public SimpleDto() {}

	public Map<String, String> getTags() {
		return tags;
	}

	public void setTags(Map<String, String> tags) {
		this.tags = tags;
	}
}
```

And a simple controller like
```
@Controller("/demo")
public class DemoController {
	@Get(uri = "/test", produces = "application/json")
	public SimpleDto test() {
		return new SimpleDto();
	}
}
```

Build to generate the DTO which will be missing the `type: object`.  Following the steps with 3.x works fine.

### Environment Information

- Majaro Linux (6.1.44-1-MANJARO)
- JDK 19

### Example Application

https://github.com/mdavis95/demo/

### Version

4.0.4

**Comment by mdavis95** [comment]
It seems in our project that changing 

```
 annotationProcessor("io.micronaut.openapi:micronaut-openapi")
``` 
to 
```
 annotationProcessor("io.micronaut.openapi:micronaut-openapi:5.1.0")
```

fixes the issue.  When will micronaut-openapi 5.1.0 be the default for micronaut?

**Comment by altro3** [comment]
This question to micronaut team. Unfortunately, I can't In what sequence the dependencies are updated :-(. As far as I understand, we now have a separate project that is responsible for all versions - https://github.com/micronaut-projects/micronaut-platform . Judging by anyway, it's not updated often :-(. so unfortunately the fastest way for you to fix the problem is to explicitly state that you want to use micronaut-openapi 5.1.0
