### ISSUE TITLE
Group properties not being read

### ISSUE THREAD

**Issue by danielvinihan** [micronaut-projects/micronaut-openapi#1267]
### Expected Behavior

Group properties set in `openapi.properties` should be read properly and respected.

### Actual Behaviour

Group properties are not read properly. 

### Steps To Reproduce

- Add group properties to a `openapi.properties` file as defined here: https://micronaut-projects.github.io/micronaut-openapi/5.1.0/guide/index.html#groups.
- Add an @OpenAPIGroup annotation to an endpoint controller as defined in the docs linked above.
- OpenAPI/Swagger files generated do not respect defined groups.

### Version

3.9.2

**Comment by altro3** [comment]
Could you add example app to reproduce problem?

**Comment by altro3** [comment]
I already see that you have fixed this error. Thank you!

**Comment by altro3** [comment]
@danielvinihan for fast fix you can move your properties to application.yml file

**Comment by danielvinihan** [comment]
@altro3 I see it's been a couple months since the last release, will there be one soon? Or should I initiate one myself using the instructions in the Readme? I could also use the fast fix you mentioned until that point.

**Comment by danielvinihan** [comment]
Actually I don't think the instructions will allow me to create a release, there is no draft release created.

**Comment by altro3** [comment]
@danielvinihan I can only ask about the release. But, in general, I would like the release to include support for ksp and a generator for Kotlin. This is not possible until micronaut-core 4.2.0 is released. I guess they are not releasing it because they want to add support for JDK 21, and this is impossible until kotlin 1.9.20 is released

Just so you understand, I'm not on the micronaut team, I'm just a contributor

**Comment by danielvinihan** [comment]
@graemerocher Are you able to include this fix in an upcoming release?
