### ISSUE TITLE
micronaut-openapi generates invalid javascript bundle path in static assets when `mapped.path` is set

### ISSUE THREAD

**Issue by skykanin** [micronaut-projects/micronaut-openapi#1474]
### Expected Behavior

When launching the application and navigating to `localhost:10210/api-docs/<rapidoc OR redoc OR swagger-ui>` the documentation loads as expected.

### Actual Behaviour

When launching the application and navigating to `localhost:10210/api-docs/<rapidoc OR redoc OR swagger-ui>` the sites don't load. Opening the console I can observe that the javascript scripts fail to load with a 404 not found error for all urls mentioned previously.

[Read this](https://github.com/skykanin/micronaut-openapi-bug-repro?tab=readme-ov-file#issue) for my theory on what causes this problem.

### Steps To Reproduce

1. `git clone https://github.com/skykanin/micronaut-openapi-bug-repro`
2. `cd` into the cloned directory
3. run `make build-mvn && make run`
4. Navigate to `localhost:10210/api-docs/redoc` for example and observe that the site doesn't load because the javascript bundle isn't found.

### Environment Information

- OS: `system: "x86_64-linux"; host os: Linux 6.7.5, NixOS, 24.05 (Uakari), 24.05.20240221.0e74ca9`
- JDK version: `21`

### Example Application

https://github.com/skykanin/micronaut-openapi-bug-repro

### Version

4.3.4

**Comment by altro3** [comment]
From documentation:
```
The path from where the swagger specification will be served by the http server defaults to `swagger`. You can change it via the `mapping.path` property.
```
As you see, this property is used solely to replace the default `swagger` path prefix with the desired value for the specification file. This does not affect UI paths.

So, to add the `/api-docs` prefix to all UI form resources, you can use one of two variants:

1. Set property `mapping.path` value `/` and add `micronaut.openapi.server.context.path=/api-docs`, like this:
```properties
micronaut.openapi.views.spec = swagger-ui.enabled=true,\
    redoc.enabled=true, \
    openapi-explorer.enabled=true, \
    rapidoc.enabled=true, \
    mapping.path=/
micronaut.openapi.server.context.path=/api-docs
```
Generated swagger-ui will be look like this:
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/523bd432-594b-4892-867f-dfad9e5b1e4b)
![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/867734eb-d699-48b9-b84d-cd3e1fded800)

2. The second variant, you need to set path to UI resources manually. because you changed default path, you nedd also tell about it to annotation processor, because it don't know your runtime configuration. You need to set right path to resources (see `swagger-ui.js.url` property in doc):
```properties
micronaut.openapi.views.spec = swagger-ui.enabled=true,\
    redoc.enabled=true, \
    openapi-explorer.enabled=true, \
    rapidoc.enabled=true, \
    mapping.path=/api-docs, \
    swagger-ui.js.url=/api-docs/swagger-ui/res/, \
    openapi-explorer.js.url=/api-docs/openapi-explorer/res/, \
    redoc.js.url=/api-docs/redoc/res/, \
    rapidoc.js.url=/api-docs/rapidoc/res/
```
Swagger UI and all views will be correct.

Both variants are suitable for you. My pleasure !
