### ISSUE TITLE
Java build fails with schemaToBind is null issue ( version 6.12.3 onwards)

### ISSUE THREAD

**Issue by vinay-sethi** [micronaut-projects/micronaut-openapi#1825]
### Expected Behavior

Java build should be completed successfully

when i use 6.12.2, everything works fine.

### Actual Behaviour

Note: Generating OpenAPI Documentation

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getExample()" because "schemaToBind" is null

### Steps To Reproduce

update the  below dependency 
annotationProcessor(group: 'io.micronaut.openapi', name: 'micronaut-openapi', version: '6.12.3')

### Environment Information

JDK 17

### Version

4.6.+

**Comment by altro3** [comment]
Try to use micronaut-openapi 6.13.0. If problem still exists. Please add a simple reproducer for this bug

**Comment by altro3** [comment]
@vinay-sethi ping

**Comment by vinay-sethi** [comment]
it was happening with 6.13.0 as well... will add a simple reproducer soon.

**Comment by altro3** [comment]
@vinay-sethi any news? Want to fix it for release 6.13.1

**Comment by vinay-sethi** [comment]
[pi-seed-app-java.zip](https://github.com/user-attachments/files/17574865/pi-seed-app-java.zip)
@altro3 i have uploaded a simple reporducer.
it application starts locally with 6.12.2 but fails to start with 6.12.3 , 6.13.0

**Comment by altro3** [comment]
@vinay-sethi Well, the problem was not in micronaut openapi, but in your code. You specified an incorrect value in the schema type. Micronaut openapi was not ready for such crooked data :-)

<img width="403" alt="{37636F1C-2716-4488-B41B-7E07F001E146}" src="https://github.com/user-attachments/assets/ef275d15-1913-4d0a-bfcf-30613c3d1a9d">

But I agree that such a situation should be handled more correctly. I added a check and next time you will see this message:
```
Error reading Swagger Schema for element [id]: {"type":"query"}
```

**Comment by vinay-sethi** [comment]
@altro3 thanks for pointing that out. the same code working in 6.12.2 is what threw me off.
