### ISSUE TITLE
Add support for validating request/responses against a OpenAPI / Swagger specification

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-openapi#21]
We use approach API first, so we do not generate OpenAPI schema, we write it manually, this allow us to use any library, and do not wait when schema generation will work with that library.

Will be great to have a tool for validating request/responses against OpenAPI / Swagger specification.
Something like https://bitbucket.org/atlassian/swagger-request-validator/src/master/

**Comment by altro3** [comment]
I think we can close this ticket because I don't see the point in doing something like this. The solution that was proposed - swagger-request-validator is extremely effective, because... The swagger file is parsed during application startup.

In my opinion, it is much more efficient to use micrornaut-openapi-generator, which will generate the necessary code at the assembly stage and add the necessary annotations so that micrornaut-validation can then process them correctly

@graemerocher wdyt?

**Comment by graemerocher** [comment]
we could write a build time validator, but it wouldn't be able to reuse the referenced implementation

**Comment by altro3** [comment]
Why is my proposal worse? The `micronaut-generator` will create classes at the assembly stage, then the `micronaut-validator` will create introspected classes also during assembly. Wouldn't this be the same as what was written about in the issue?

**Comment by graemerocher** [comment]
never said it was worse, but yeah I don't see the value of these request validators if you are generating from spec

**Comment by altro3** [comment]
Okay, then I'll close this issue. The working solution is:

1. Generate classes according to the OpenAPI specification using `micronaut-openapi-generator`.

2. Add `micronaut-validation` and get what is written in the issue: validation requests according to the openapi specification
