### ISSUE TITLE
Add support for the Swagger codegen CLI project

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-openapi#517]
See https://github.com/swagger-api/swagger-codegen

**Comment by debuglevel** [comment]
Great idea, that would be wonderful! Especially generating Micronaut declarative HTTP clients would be nice.

There are at least two OpenAPI code generators: https://github.com/swagger-api/swagger-codegen is the legacy project by Swagger/Smartbear (not much happening since early 2018) while https://github.com/OpenAPITools/openapi-generator is the active community-driven fork.

**Comment by psoares** [comment]
I've been wanting this for ages. I definitely recommend using openapi-generator instead. 
Here are a few pointers:
- https://openapi-generator.tech/docs/templating
- The Springboot generator template, as an example: https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/JavaSpring

**Comment by graemerocher** [comment]
`openapi-generator` support is being worked on based on what is there for Spring, we will let you know when there is something to try out

**Comment by Larkhis** [comment]
The new open api generator java-micronaut-client on beta version was finally released.
See [https://openapi-generator.tech/docs/generators/java-micronaut-client](https://openapi-generator.tech/docs/generators/java-micronaut-client)
