### ISSUE TITLE
Add support for generating OpenAPI V2 specs

### ISSUE THREAD

**Issue by stottpaul** [micronaut-projects/micronaut-openapi#80]
Various frameworks including:
- OWASP ZAP (https://github.com/zaproxy/zaproxy/issues/4549) 
- Google Cloud Endpoints (https://cloud.google.com/endpoints/docs/openapi/openapi-limitations)

will only work off OpenAPI v2 specs.    
It would be helpful if there was an option in Micronaut to generate any major version of the OpenApi spec.

**Comment by yosuf** [comment]
Also, WSO2 API manager supports only until 3.0.0. 
It would be favourable if the OpenAPI version to generate is configurable.

**Comment by ilopmar** [comment]
I'm closing this because I don't see feasible to keep two (or even more) different implementations at the same time.

Besides that, one thing to keep in mind is that OpenAPI 2.0 is way to old and that 3.0.0 was released on 2017, so almost 4 years ago (see https://swagger.io/specification/#appendix-a-revision-history):

![image](https://user-images.githubusercontent.com/559192/129020211-a74d66cd-c58d-486a-8293-dc826a12c2b0.png)

So, instead of us generating old and deprecated specs, those tools should upgrade to use the latest versions of the spec.
