### ISSUE TITLE
Gradle print some debug logs during OpenApi generation

### ISSUE THREAD

**Issue by francesco-monorchio** [micronaut-projects/micronaut-openapi#854]
### Expected Behavior

Logs should not be too verbose.

### Actual Behaviour

Hi all,

From version 3.7.4 of Micronaut, the OpenApi module start to print a lot of debug logs and I want to disable/hide them.
Ex.:
```
> Task :sources:services:storage-engine:compileIntegrationTestGroovy
WARNING: Can't identificate projectPath

> Task :sources:services:user-service:compileGroovy
22:15:21.968 [/127.0.0.1:49194 to /127.0.0.1:43175 workers] DEBUG io.micronaut.context.env.DefaultEnvironment - Environment deduction is using the default of: true
22:15:21.980 [/127.0.0.1:49194 to /127.0.0.1:43175 workers] DEBUG io.micronaut.context.env.DefaultEnvironment - Starting environment io.micronaut.openapi.visitor.AnnProcessorEnvironment@64fcb24 for active names []
22:15:21.993 [/127.0.0.1:49194 to /127.0.0.1:43175 workers] DEBUG io.micronaut.context.env.AbstractPropertySourceLoader - No PropertySource found for file name: application.VCAP_APPLICATION
22:15:21.994 [/127.0.0.1:49194 to /127.0.0.1:43175 workers] DEBUG io.micronaut.context.env.AbstractPropertySourceLoader - No PropertySource found for file name: application.json
22:15:21.994 [/127.0.0.1:49194 to /127.0.0.1:43175 workers] DEBUG io.micronaut.context.env.AbstractPropertySourceLoader - No PropertySource found for file name: application.json
22:15:21.994 [/127.0.0.1:49194 to /127.0.0.1:43175 workers] DEBUG io.micronaut.context.env.AbstractPropertySourceLoader - No PropertySource found for file name: application.VCAP_SERVICES
22:15:21.995 [/127.0.0.1:49194 to /127.0.0.1:43175 workers] DEBUG io.micronaut.context.env.AbstractPropertySourceLoader - No PropertySource found for file name: application.properties
22:15:21.996 [/127.0.0.1:49194 to /127.0.0.1:43175 workers] DEBUG io.micronaut.context.env.AbstractPropertySourceLoader - Found PropertySource for file name: application.yml
Note: Generating OpenAPI Documentation
```

### Steps To Reproduce
Run ./gradlew clean build --no-build-cache

### Environment Information

OpenSUSE Tumbleweed
JDK 17.0.5

### Example Application
Repo: https://github.com/francesco-monorchio/micronaut-samples/tree/openapi-logs
Branch: openapi-logs

### Version

3.7.4

**Comment by altro3** [comment]
@francesco-monorchio Which micronaut openapi version do you use? Try latest version Micronaut OpenAPI v4.7.1 , maybe it's already fixed.

If no, could you add example project to reproduce this case?

**Comment by francesco-monorchio** [comment]
@altro3 I am using Micronaut OpenAPI 4.5.2. Move forward to 4.7.1 do not resolve the problem. And sure, in a short time I will share an example project about this issue. :-)

**Comment by francesco-monorchio** [comment]
@altro3 I have updated the issue with a sample repo.

**Comment by altro3** [comment]
@francesco-monorchio Thank you! Hmmm... interesting. I want to say right away: this problem is specific only for working with grooves. Debug information is not displayed when you work with Java or Kotlin.

Well, I can say for sure that this is not a bug in Micronaut OpenaAPI , because this annotation processor itself does not write anything to the log and does not use slf4j, but micronaut inject uses it. I've been looking for an option to turn off logging for the groove compiler, but I haven't been able to find one. Perhaps this is the specifics of how the gradle works with grooves, I don't know.

@graemerocher I think you should look at this problem, because I don't know how to fix it.

**Comment by altro3** [comment]
@francesco-monorchio Well, I know how to solve the problem in your example. Just change the dependency:
```groovy
implementation 'ch.qos.logback:logback-classic'
```
to it:
```groovy
runtimeOnly 'ch.qos.logback:logback-classic'
```

**Comment by graemerocher** [comment]
this is unfortunately because Groovy doesn't isolate the annotation processor classpath like Java does

**Comment by francesco-monorchio** [comment]
Hello guys and thanks for your support. Unfortunately, in my project I need that dependency at compile time because I have some custom implementations of logback classes. In Micronaut 3.6.x branches there is no problem at all so my question is... from what groovy version the bug has been introduced? I can try to downgrade the groovy version.

**Comment by altro3** [comment]
@francesco-monorchio In general, several points can be distinguished from the foregoing:

1. This problem is not related to micronaut-openapi and I can't fix it.
2. The problem arises due to the fact that logback gets into the dependency of the annotationProcessor level. Because micronaut-openapi depends on micronaut-core, which uses slf4j , logging is done automatically.
3. This problem only occurs when using groovy (version doesn't matter). The problem is due to the specifics of groovy - groovy does not distinguish between annotationProcessor and compile levels.

The only solution I described above. Unfortunately, nothing else can be done at the moment.

**Comment by francesco-monorchio** [comment]
Ok, thanks for the response. Just last question. These logs are printed because we start the context (during compilation) to resolve placeholders from Environment right? If I don't need it, can we try to enable/disable it with a property in openapi.properties?

**Comment by altro3** [comment]
@francesco-monorchio You got it right. I fixed the problem: now if you disable environment support in your case, nothing will be displayed in the logs

**Comment by francesco-monorchio** [comment]
Thanks for your support. :-)

**Comment by altro3** [comment]
My pleasure! Wait for release 4.8.2
