### ISSUE TITLE
OpenAPI - Use of multiple modules has conflict in view layer

### ISSUE THREAD

**Issue by weesftw** [micronaut-projects/micronaut-openapi#914]
I have a project structured in a multi-module schema, and each module has its controllers which in turn have the mapping with Swagger annotations. However, if I add all of them into a single structure, the view layer only displays the first module, ignoring the others, without having an iteration to load all the classpath endpoints. Is there anything I can do to resolve this issue and make all endpoints appear in the Swagger documentation UI?

I explained it in detail in an open issue on `micronaut-openapi` with an example application: [#810](https://github.com/micronaut-projects/micronaut-openapi/issues/810)

**Comment by altro3** [comment]
I wrote to you what needs to be written in your example so that endpoints from classes from included jar files are added.

Naming shouldn't be a problem. You can also use the new feature to group endpoints as you need into different swagger files. But support for groups will be in release 4.10.0 very soon. You can see a preview of the feature here: https://github.com/micronaut-projects/micronaut-openapi/pull/1067
