### ISSUE TITLE
Loading of Environment properties should be in sync with the running application.

### ISSUE THREAD

**Issue by francesco-monorchio** [micronaut-projects/micronaut-openapi#944]
### Feature description

This project is very awesome but i don't like so much the loading of the Environment at compile time.
Groovy has a lot of problems with it. For example it prints a lot of debug log even when "micronaut.environment.enabled" is disabled. And another problem is that the generated schema sometimes is not in sync with the running application due to the fixed environments in openapi.properties during compilation that can be different from that in MICRONAUT_ENVIRONMENTS at runtime.

In my project, I have resolved some of the problems, using a sort of placeholders during compile time generation of the schema and exposing the yml or json specification file through an endpoint that before returning it do placeholder substitution based on the current environment.

I did a simple example repo to demonstrate this process here (https://github.com/francesco-monorchio/micronaut-openapi-example). WDYT?

Thanks,
Frank

**Comment by altro3** [comment]
@francesco-monorchio Hi! Unfortunately, these are limitations of the annotation processor. It always runs BEFORE compiling the project. This allows you not to add additional dependencies at the start of the application and separate business logic and auxiliary logic.

The only solution that I see is an additional module for processing placeholders at application start, but it looks like a crutch.

**Comment by francesco-monorchio** [comment]
I know that Groovy has problems with annotation processors :-( . But, instead, what about the placeholder substituion at runtime?
Why do you think it is a crutch? In that way we can dinamically update the schema based on the current active environments with no change and especially no rebuild. Have you looked at my implementation? It's not perfect for sure, but for me, can be a good improvement. :-)

**Comment by altro3** [comment]
Actually, no one forbids you to substitute placeholders in swagger.yaml at the start of the application. Wait, you need to write a custom handler for this and generate the final swagger.yaml when the application starts. The annotation processor cannot physically do this, because it does not participate in the launch of the final application and generates the swagger file before compilation.

That's why I say that the only solution is to write a separate code that will be executed when the application starts to generate a swagger file with substituted placeholders. But I see no reason to strain so much in such a simple and particular case.

My vision is this: you can write the code yourself that loads the generated swagger file, substitutes placeholders and creates the final swagger file, such as you need
