### ISSUE TITLE
SWAGGER-UI giving 404 not found

### ISSUE THREAD

**Issue by kamalbhatia528** [micronaut-projects/micronaut-openapi#959]
### Issue description

PLEASE GUIDE!! ALSO EXPLORED DOCUMENTATION NOTHING FOUND

SWAGGER-UI giving 404 error, I have generated the project from micronaut launch with latest version and Java 17, I have selected the OPEN API and swagger feature, 

I am hitting this url http://localhost:8080/swagger-ui but getting 404 not found, Am I missing something ?

Thanks in advanc

**Comment by altro3** [comment]
I think you need create issure here: https://github.com/micronaut-projects/micronaut-starter/issues

That's not a problem of micronaut-openapi

**Comment by altro3** [comment]
Also you can add your application.yml configuration here. I think problem with not configured routing to swagger-ui resources

**Comment by altro3** [comment]
About documentation. Look here https://micronaut-projects.github.io/micronaut-openapi/4.8.5/guide/index.html#swaggerui

![изображение](https://user-images.githubusercontent.com/48474279/227733951-35cab014-c9e6-4f47-bccf-9d2fb031ca07.png)

Did you read it?

**Comment by kamalbhatia528** [comment]
@altro3 , I am using the same config but still its giving me 404, you can also try the same byt generating the project from below link
https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=GRADLE&test=JUNIT&features=openapi&features=swagger-ui&features=azure-function&version=3.8.7

**Comment by kamalbhatia528** [comment]
its not working with Azure function actually, Also raised this issue https://github.com/micronaut-projects/micronaut-azure/issues/449

**Comment by altro3** [comment]
@kamalbhatia528 I don't know how azure works. But if you choose netty to run, then everything works fine
![изображение](https://user-images.githubusercontent.com/48474279/228828637-3f72c2fb-1125-4cc8-bd41-4b29ab083789.png)

![изображение](https://user-images.githubusercontent.com/48474279/228828783-df19048c-2271-4304-9a89-b77f0114988d.png)

**Comment by kamalbhatia528** [comment]
Yes, I agree its working if I will run the application directly
I have also raised the issue on Micronaut Azure repo https://github.com/micronaut-projects/micronaut-azure/issues/449

**Comment by altro3** [comment]
I still think that the problem in project https://github.com/micronaut-projects/micronaut-starter, wich generate this demo project. and something is wrong with generated configuration

**Comment by altro3** [comment]
@kamalbhatia528 Hi! I looked again at the example that is generated in the starter. In general, the swagger file itself and the swagger ui files are generated normally. But I have no idea how to access these files using azure. You did the right thing by creating a ticket in the micronaut-azure project. Unfortunately, I'm not on the micronaut's team and I'm doing all this on my own initiative and can't help in any way with solving this problem.

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/ca53c572-16f3-4535-a0e7-9aee77cf55e1)

But I can say for sure that the problem is not with micronaut-openapi , because this library worked as it should
