### ISSUE TITLE
Empty properties when using `@Table` annotation and Groovy subprojects

### ISSUE THREAD

**Issue by tcrespog** [micronaut-projects/micronaut-openapi#964]
### Expected Behavior

The properties in the generated spec of a response class are properly populated when the class of one of its attributes is annotated with `javax.persistence.Table` regardless of the project structure (subprojects) and the language (Groovy).

### Actual Behaviour

- Given a project made of two Groovy subprojects.
- And, in the first subproject, two classes: 
   - `Pet`: JPA `@Entity` class.
   - `GetPetResponse`: wrapper of the `Pet` class.
- And, in the second subproject, a single `@Controller` class and method that returns a `GetPetResponse` object as response body.
- When the `Pet` class contains the `@Table` annotation, the generated spec of `GetPetResponse` does not include the expected properties.

Any of the following actions make it work:
- Removing the `@Table` annotation.
- Moving the `GetPetResponse` class to the subproject where the `@Controller` class is located.
- Using Java instead of Groovy.  

### Steps To Reproduce

1. Download the `mn-openapi-table-issue` sample project.
2. Build the `app` subproject and check the generated OpenAPI YML spec (at `app/build/classes/groovy/main/META-INF/swagger`): the `properties` section of `GetPetResponse` is empty.
3. Remove the `@Table` annotation in `Pet`.
4. Re-build the `controllers` subproject and check the generated OpenAPI YML spec: the `properties` section of `GetPetResponse` is properly populated.

### Environment Information

JDK version: 17
Language: Groovy

### Example Application

https://github.com/tcrespog/mn-openapi-table-issue

### Version

3.8.7

**Comment by altro3** [comment]
@tcrespog Hi! It turned out to be one of the hardest bugs to reproduce :-). After several hours of analysis, I finally found the problem.

So, the problem arises because of a bug in the `io.micronaut.data:micronaut-data-hibernate-jpa` library (and the `io.micronaut.sql:micronaut-hibernate-jpa` library). The problem occurs when processing the `@Table` annotation and only when working with groovy. Unexpected behavior when processing the `indexes` annotation attribute. The problem only occurs if this field is an empty array.

I will fix the bug in these libraries and everything will be fine in the next release.

In order not to wait for a new release, I came up with a quick fix for you: just add one Index annotation to the Table annotation. Like that:
```groovy
@Table(name = 'petstore_pet', indexes = @Index)
```

**Comment by altro3** [comment]
@tcrespog Fixed here: https://github.com/micronaut-projects/micronaut-data/pull/2094. Wait new release micronaut-data

**Comment by tcrespog** [comment]
Thanks a lot for the fix and the workaround.

**Comment by altro3** [comment]
@tcrespog Try to use Micronaut Data 3.9.7. Everything must be fine now

**Comment by tcrespog** [comment]
I can confirm that upgrading the sample app to Micronaut 3.8.8, which has Micronaut Data 3.9.7 as a dependency, solves the problem. Thanks again.
